services:
  sstp_vpn:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ppp
    ports:
      - "80:443"
    volumes:
      - ./logs/vpn:/var/log/vpn
      - ./logs/squid:/var/log/squid
      - ./src/squid.conf:/etc/squid/squid.conf
    command: ["/home/scripts/sstp_starter.sh"]